server:
  port: 9090

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courseDb
    username: postgre
    password:
  jpa:
    hibernate:
      #Crear autom?ticamente las tablas
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    #Para que no de errores no es el configserver verdadero solo es para evitar errores
    import: optional:configserver:http://localhost:8888

#REGISTRADO EN EUREKA
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
